<?php

namespace App\Services;

use App\Models\RadiusNas;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Process;
use RuntimeException;

class RadiusClientsSynchronizer
{
    public function __construct(
        private readonly Filesystem $filesystem,
    ) {}

    /**
     * @throws FileNotFoundException
     */
    public function sync(): void
    {
        $payload = $this->buildPayload();
        $path = (string) config('radius.clients_path');
        $directory = dirname($path);

        if ($path === '') {
            throw new RuntimeException('Path clients.conf FreeRADIUS belum diatur.');
        }

        $canWrite = $this->filesystem->isDirectory($directory)
            && $this->filesystem->isWritable($directory)
            && (! $this->filesystem->exists($path) || $this->filesystem->isWritable($path));

        if (! $canWrite) {
            throw new RuntimeException("Tidak dapat menulis ke {$directory}. Periksa izin direktori FreeRADIUS.");
        }

        $this->filesystem->put($path, $payload);
        $this->reloadRadius();
    }

    public function buildPayload(): string
    {
        $nasClients = RadiusNas::query()
            ->active()
            ->orderBy('name')
            ->get();

        return $this->buildClientsPayload($nasClients);
    }

    /**
     * @param  Collection<int, RadiusNas>  $nasClients
     */
    public function buildClientsPayload(Collection $nasClients): string
    {
        $lines = [
            '# Generated by Rafen Self-Hosted - do not edit manually',
            '# Updated at '.now()->format('Y-m-d H:i:s'),
            '',
        ];

        foreach ($nasClients as $nasClient) {
            $secret = addslashes($nasClient->secret);
            $requireMessageAuthenticator = $nasClient->require_message_authenticator ? 'yes' : 'no';

            $lines[] = "client {$nasClient->shortname} {";
            $lines[] = "    ipaddr = {$nasClient->ip_address}";
            $lines[] = "    secret = {$secret}";
            $lines[] = "    shortname = {$nasClient->shortname}";
            $lines[] = "    require_message_authenticator = {$requireMessageAuthenticator}";
            $lines[] = '    nas_type = mikrotik';
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function reloadRadius(): void
    {
        $command = trim((string) config('radius.reload_command', ''));

        if ($command === '') {
            return;
        }

        $process = Process::run($command);

        if (! $process->successful()) {
            throw new RuntimeException('Reload FreeRADIUS gagal: '.trim($process->errorOutput() ?: $process->output()));
        }
    }
}
